[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
degen_cash = "955SPKk3hC8cbqmophEAMigzaPDBrtHnVzWWS8JN6tr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/degen_cash.ts"

[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/Users/spacemandev/Projects/degen_cash/artifacts/arcium_program_0.3.0.so"

[[test.validator.account]]
address = "FHriyvoZotYiFnbUzKFjzRSb2NiaC8RPWY7jtKuKhg65"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "7MGSS4iKNM4sVib7bDZDJhVqB6EcchPwVnTKenCY1jt3"
filename = "artifacts/arcium_fee_pool.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint.json"

[[test.validator.account]]
address = "2qPRnmigG7KBwnR26djXHdPuYBzBvYEsbZBeoNVeWzqr"
filename = "artifacts/wallet_acc_2qPR_Wzqr.json"

[[test.validator.account]]
address = "5zwbVVsCWny2eNVVrGPh9uACsJv99Qw11sNF4dP9ohP4"
filename = "artifacts/arx_ata_2qPR_Wzqr.json"

[[test.validator.account]]
address = "CJLCMJb6nc5o9UUqMBMAc5xFWXwRMQzCzdoc9GkhNrAS"
filename = "artifacts/wallet_acc_CJLC_NrAS.json"

[[test.validator.account]]
address = "EGnXybruHkcByiPZRCxAQEWM5Tnd7xgBNi9wsDxSq8ri"
filename = "artifacts/wallet_acc_callback_EGnX_q8ri.json"

[[test.validator.account]]
address = "azD2NdDXBe2F6qGGcrX8QQWy3hPUGQwF9TcTNZVxAW6"
filename = "artifacts/arx_ata_CJLC_NrAS.json"

[[test.validator.account]]
address = "ENAanR8zemRsReMw1SFviEHbisV28YiEuVSCxfy9HWKu"
filename = "artifacts/operator_acc_CJLC_NrAS.json"

[[test.validator.account]]
address = "ELoRR19zrps1G3UYKcAxr7LKbw3kbqkVUXVY9dETMWN7"
filename = "artifacts/arx_node_CJLC_NrAS.json"

[[test.validator.account]]
address = "6MPtcD8SrCJAEtSw6dN3NmG49A81cFpN8nkmMV5hpwFr"
filename = "artifacts/wallet_acc_6MPt_pwFr.json"

[[test.validator.account]]
address = "4Qt1qDve6QzsKH74YWSuJ93mUbwfTFS3KMW5f2vz8Vqf"
filename = "artifacts/wallet_acc_callback_4Qt1_8Vqf.json"

[[test.validator.account]]
address = "2z2msvUcXdmsXVQmvLTSKqB7kwytrcXcNBko1gZv87bB"
filename = "artifacts/arx_ata_6MPt_pwFr.json"

[[test.validator.account]]
address = "49GByKtwG1uYfvYXzVFt8URJxzimzKCPkSNguVvkWtf8"
filename = "artifacts/operator_acc_6MPt_pwFr.json"

[[test.validator.account]]
address = "XdfSwb8ZajhN7CerfBSJVhyfx5fyLtv34QVKSRgMFA9"
filename = "artifacts/arx_node_6MPt_pwFr.json"

[[test.validator.account]]
address = "GgSqqAyH7AVY3Umcv8NvncrjFaNJuQLmxzxFxPoPW2Yd"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "4uzxaAYfUqGf2thYudKwrCqHPZfFyW37ZNwvUCQhf1vA"
filename = "artifacts/init_global_dc_mint_raw_circuit_0.json"

[[test.validator.account]]
address = "DwPt6Ub9fHrAQC1QzzoVXgEF7EMan99xainWSrmSQWTH"
filename = "artifacts/mxe_keygen_comp_def.json"

[[test.validator.account]]
address = "AMVxQeTfjAEvjXa3kErKaK3QgH2yYVorv254ZwACfNPk"
filename = "artifacts/mxe_keygen_comp.json"

[[test.validator.account]]
address = "J3b44Ja11tVJaSDfV3aAiuFCuRbKKNuZAs5TzTsQPHUq"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "E5fVbPL82Zk6P3Dv1pm1VcAMrJTVvE3Q34VwNmrX2neV"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "22cJn64DarsPmoYuVhxjWzEqTRtyEp2uRzTE2oSkbZK8"
filename = "artifacts/executing_pool_acc.json"
